### ISSUE TITLE
Service

### ISSUE THREAD

**Issue by shahbaz17** [shahbaz17/theindianwave#2]
Write about service . What and how it is different from others?

**Comment by imox2** [comment]
**What is so different about us?**

For the most part we are same as your next door website developer (or soup maker as we say it). So why would you work with us. You want soup and you come to us and your problem ends there. From there the problem is our problem and not yours. We will make the soup and will make sure the soup remains warm, no extra cost for warming. 

**We may say a lot about us. But you will never know about it until you give us a chance. If you want to make omelette, you will have to break some eggs.**
